### ISSUE TITLE
hey, svelte lover ❤

### ISSUE THREAD

**Issue by gauravjatt4k** [humanspeak/svelte-markdown#1]
I know you have updated your svelte-markdown npm package but I have found an error which was the old package, it used to render on ssr only, but it is happening in the browser, please fix it soon.

**Comment by jaysin586** [comment]
Can you provide an example so that I can look?

**Comment by devgauravjatt** [comment]
![Annotation 2024-11-09 190505](https://github.com/user-attachments/assets/22f280fd-bc19-4880-9468-c3e18f0f12ef)

check this image in after website is render show browser in render md to html way and how to fix it 😥


https://www.npmjs.com/package/svelte-markdown

this is working fine but old code base

**Comment by jaysin586** [comment]
I believe most if not all of the issues you were seeing were completed in the `0.6.1` release. I am going to close this issue, please feel free to let me know if it does not meet your needs.
