### ISSUE TITLE
![Annotation 2024-11-09 190505](https://github.com/user-attachments/assets/22f280fd-bc19-4880-9468-c3e18f0f12ef)

### ISSUE THREAD

**Issue by jaysin586** [humanspeak/svelte-markdown#7]
![Annotation 2024-11-09 190505](https://github.com/user-attachments/assets/22f280fd-bc19-4880-9468-c3e18f0f12ef)

check this image in after website is render show browser in render md to html way and how to fix it 😥

https://www.npmjs.com/package/svelte-markdown

this is working fine but old code base

_Originally posted by @devgauravjatt in https://github.com/humanspeak/svelte-markdown/issues/1#issuecomment-2466219016_

**Comment by jaysin586** [comment]
@devgauravjatt do you have some example code for me to check out? I am currently working on the HTML engine as the `@html` tag does not work the same as it did in Svelte4

**Comment by jaysin586** [comment]
I believe most if not all of the issues you were seeing were completed in the `0.6.1` release. I am going to close this issue, please feel free to let me know if it does not meet your needs.

**Comment by devgauravjatt** [comment]
no fix bro same problem  --- https://github.com/dollyjat/svelteMd ----- clone and check error is client side render markdown to html not work in sever
